server:
  port: 3000
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 400
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true
# DataSource Config
spring:
  application:
    name: ririra-echo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ririra?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root